### ISSUE TITLE
Contour doesn't open: Unhandled error caught. Error loading glyph. invalid size handle

### ISSUE THREAD

**Issue by milochadam** [christianparpart/contour#112]
### Error:
`Unhandled error caught. Error loading glyph. invalid size handle`
The binary was run from another terminal (gnome-terminal)

### OS:
`Linux manjaro 5.4.43-1-MANJARO`

### contour.yml font setting:
```yml
fontFamily: "Fira Code, Hack, Ubuntu Mono, Consolas, monospace"
```
I have FiraCode installed, so it should be picked:

```
$ fc-match 'Fira Code'
FiraCode-Regular.ttf: "Fira Code" "Regular"
```

### Keyboard layout:
`Polish`

**Comment by christianparpart** [comment]
@milochadam Can you please try the branch origin/font-graceful-error-handling from PR https://github.com/christianparpart/contour/pull/113?

If it is not fixing it, you should at least see the fatal error with more details printed.

p.s.: What's your locale? I'm still trying to figure why you're getting that error.

**Comment by milochadam** [comment]
#### The error is:
```
Unhandled error caught. Error loading glyph index 0 for font /usr/share/fonts/TTF/Vera.ttf; invalid glyph index
```

#### Locale:
```
LANG=en_US.UTF-8
LC_CTYPE=
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

**Comment by christianparpart** [comment]
I was giving it another round by avoiding loading glyph index 0. Can you try again please?

FYI: I'll have some family soon, will check back ASAP.

**Comment by milochadam** [comment]
It fails on another glyph:
```
Unhandled error caught. Error loading glyph index 48 for font /usr/share/fonts/TTF/Vera.ttf; invalid glyph index
```

**Comment by christianparpart** [comment]
Hi, it is really interesting, why the heck is Vera.ttf in your font list.

* Is this happening at startup already or when you type/execute specific commands?
* Can you please paste (inside of tripple backticks or a link to gist.github.com) your contour.yml?
* What's the output of `fc-match -s ThatFontYouAreUsing`? I assume you're not doing anything bold/italic, but if you are curious, do it also for your bold font family, such as (`fc-match -s "Fira Code:style=bold"`) and paste that output as well.

I really wonder what Vera is doing, but I try to reproduct that with Vera locally, too

Many thanks for your feedback. :-)

**Comment by milochadam** [comment]
It's happening at startup.

#### Config file:
https://gist.github.com/milochadam/c908e6601c22dfcb6af1a6825faca7fa

#### Fonts

- `fc-match -s "Fira Code"`
https://gist.github.com/milochadam/f93daa8ab0173bb59b2aad0bcd5e4340

- `fc-match -s "Fira Code:style=bold"`
https://gist.github.com/milochadam/cb9d27ad3e1db7db622dd37eb30e0990

- `fc-match -s "Fira Code:style=italic"`
https://gist.github.com/milochadam/34d6fd91f11c1fdcab59f17e9990934c

**Comment by christianparpart** [comment]
Hey. Please use the config file from

https://github.com/christianparpart/contour/blob/wip/src/contour/contour.yml

Because this morning I was streamlining the configuration keys to all being
snake,_case, and your config file shows the old convention. Can you give
that a try?

Thanks.

**Comment by milochadam** [comment]
Still the same error and there seem to be additional Qt error. I'm pretty sure it wasn't here before but it's possibly something with my machine. 
```
Qt: Session management error: Could not open network socket
Unhandled error caught. Error loading glyph index 48 for font /usr/share/fonts/TTF/Vera.ttf; invalid glyph index
```

**Comment by milochadam** [comment]
Unfortunately it still doesn't work.

**Comment by milochadam** [comment]
After restarting my machine Qt error disappeared but the terminal still won't open

**Comment by christianparpart** [comment]
Please `git pull` that branch and test again, if you don't mind.

I think it is now the most graceful way to get it. It might be interesting to see what is happening now, and if it is failing, what the output will be.

Many thanks for testing. :)

**Comment by christianparpart** [comment]
Last note for tonight: After having a chat with someone on Twitch with (interestingly) almost the same name as you 😇 - he also had the very same issue, and what was fixing it on his side is this commit:

https://github.com/christianparpart/contour/pull/113/commits/9de23b39426d7fe9c95e286b99a39747254728f3

it's part of the current proposed PR, so please just git pull and I'm happy to merge ASAP. ;)

Have a good night,
Chris.

**Comment by milochadam** [comment]
That indeed fixed it. Thanks!
