### ISSUE TITLE
Support Sixel Graphics

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#116]
Support rendering graphics using Sixels.

### Status

sixel images can be basically displayed, but for a release at least eviction needs to be implemented, too (see Checklist).

### See
- https://www.vt100.net/docs/vt3xx-gp/chapter14.html
- https://en.wikipedia.org/wiki/Sixel
- https://github.com/saitoha/libsixel

### client application support

- gnuplot
- img2sixel
- `neofetch --backend sixel`
- tmux (via branch, incomplete?)
- screen (via branch, incomplete?)
- w3m (terminal based web browser, via `-sixel`)
- ranger (file manager, via w3m's internal w3mimgdisplay)
- ... who else

### Other terminals supporting this:

* xterm
* mlterm
* libvte ticket: https://gitlab.gnome.org/GNOME/vte/-/issues/254 and https://bugzilla.gnome.org/show_bug.cgi?id=729204#c38
* Terminator ticket: https://bugs.launchpad.net/terminator/+bug/1562514
* Windows Terminal: https://github.com/microsoft/terminal/issues/448
* ST: via patch only https://gist.github.com/saitoha/70e0fdf22e3e8f63ce937c7f7da71809
* wezterm: WIP via https://github.com/wez/wezterm/issues/217
* ... (others?)

### Checklist

- [x] Sixel parser (with unit tests)
- [x] Sixel image builder
- [x] display Sixel image in terminal
- [x] image pool resource eviction
- [x] respect sixel scrolling (`SM`/`RM` `?80`)
- [x] respect default background color
- [x] implement `SM/RM ?1070` (use private color registers)
- [x] texture atlas allocator to support eviction and reuse
- [x] implement `CSI ? Pi ; Pa ; Pv S` (XTSMGRAFICS)
- [ ] respect aspect ratio from Sixel (DCS and `DECGRA` (Set Raster Attributes " Pan; Pad; Ph; Pv)

### For later

- `RasterizedImage` must support image AlignmentPolicy and ResizePolicy, but both is not necessarily required for Sixel.

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/217 is tracking this feature in wezterm and has some notes from the [jexer](https://jexer.sourceforge.io/sixel.html) author about supporting/testing sixels.  FWIW, the way I implemented this was first to implement the iterm2 image protocol, and then make sixels work on top of that mechanism.

**Comment by christianparpart** [comment]
Aspect Ratio can be done in a seperate ticket.
