### ISSUE TITLE
segmentation fault when setting width or height to 0

### ISSUE THREAD

**Issue by milochadam** [christianparpart/contour#117]
```
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FT_Select_Charmap failed. Ignoring; invalid charmap handle
FontLoader: loading font "Fira Code" from "/usr/share/fonts/TTF/FiraCode-Regular.ttf", size=12, fallbacks=53
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "Fira Code:style=bold" from "/usr/share/fonts/TTF/FiraCode-Bold.ttf", size=12, fallbacks=55
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "Fira Code:style=italic" from "/usr/share/fonts/TTF/FiraCode-Regular.ttf", size=12, fallbacks=55
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "Fira Code:style=bold italic" from "/usr/share/fonts/TTF/FiraCode-Regular.ttf", size=12, fallbacks=55
Failed to FT_Set_Pixel_Sizes: invalid pixel size
FontLoader: loading font "emoji" from "/usr/share/fonts/TTF/Symbola.ttf", size=12, fallbacks=46
OpenGL type     : OpenGL
OpenGL renderer : AMD TAHITI (DRM 2.50.0, 5.4.43-1-MANJARO, LLVM 10.0.0)
OpenGL version  : 4.5
GLSL version    : 4.50 (450, 440, 430, 420, 410, 400, 330, 150, 140, 130, 120, 320 es, 310 es, 300 es, 100)

Resized to pixelSize: 910x449, screenSize: 130x29, margin: 0x14, cellSize: 7x15
Resized to pixelSize: 910x360, screenSize: 130x24, margin: 0x0, cellSize: 7x15
[1]    9682 segmentation fault (core dumped)  contour
```

**Comment by christianparpart** [comment]
This is obvious. Thanks a lot. I should add some guards to be more defensive. Nice catch. This is an easy fix, but questionable what the best solution would be.

1.) Fatal exit and say the reason (invalid font size), or
2.) Fallback to some default size, say 12pt.

**Comment by milochadam** [comment]
I wouldn't want my terminal to close since I could have done that by mistake, so maybe set minimal window size?

**Comment by uspasojevic96** [comment]
I would like to add that default values for everything would be nice or to have some shortcut to reload config because my contour crashed when i was moving around config file to my dotfiles to link

**Comment by christianparpart** [comment]
So a shortcut action for `ReloadDefaultConfig` and `ReloadConfig`. Both sound reasonable.

Yet it should not have crashed. I wonder how I could find out why that have happened to you.

**Comment by uspasojevic96** [comment]
It crashed because i moved the actual config file and thanks to watcher for config changes it tried to load nonexisting file before remaking it (which caused the terminal to crash)

**Comment by christianparpart** [comment]
Recently addressed in `wip` branch. A minimum with (of 6pt) is required.
