### ISSUE TITLE
Contour launches but nothing happens

### ISSUE THREAD

**Issue by sonulohani** [christianparpart/contour#122]
Hi,

I build contour application in windows 10 2004 using vs2019 in x64 arch. When I launch contour application nothing happens.

**Comment by christianparpart** [comment]
Good morning. Many thanks for your interest in Contour. While this app is still in very active but also rather early development, I think I would need a little more information on order to reproduce. Did you start a debug build and die you theck the conhost's console output? Is this an up-to-date with indoww 10? And what branch gav you been building?

Best regards,
Christian.

**Comment by sonulohani** [comment]
Hi @christianparpart 

I debugged the application and its throwing exception at ```return loadConfigFromFile((configHome() / "contour.yml").string(), _logger);``` in Config.cpp with the exception message :- Exception thrown at 0x00007FFDD4B23E49 in contour.exe: Microsoft C++ exception: YAML::ParserException at memory location 0x000000BB182FAF50.

**Comment by christianparpart** [comment]
@sonulohani 

What's the contents of your contour.yml - did you modify it, or is it the one default-shipped with the binary?

What branch did you use to build contour? (NB: I'm also soon to merge `wip` into `master` branch).

**Comment by sonulohani** [comment]
Hi @christianparpart 

I had just cloned your repository and followed README.md to build the source code. No modification in any source file.

**Comment by sonulohani** [comment]
Here is the yml file

[contour.yml.txt](https://github.com/christianparpart/contour/files/4840258/contour.yml.txt)

I dont understand whats the last line in yml.

**Comment by uspasojevic96** [comment]
That last line might be the issue, it's not valid YAML syntax. @christianparpart are you taking into account the windows CRLF?

**Comment by christianparpart** [comment]
> That last line might be the issue, it's not valid YAML syntax. @christianparpart are you taking into account the windows CRLF?

Thanks for testing. Yes, the last line is indeed wrong. I am almost certain the yaml file is being generated with Unix like endings. I am more concerned about what the tail of your yaml file is, though.  I am checking ASAP.

**Comment by sonulohani** [comment]
Hi @christianparpart 

Please see the ```default_config_yaml``` array in the generated contour_yaml.h.txt file. The ending part has some null values. 

[contour_yaml.h.txt](https://github.com/christianparpart/contour/files/4842337/contour_yaml.h.txt)

**Comment by christianparpart** [comment]
Update: https://github.com/christianparpart/contour/commit/5442d36734f4fd4cbc32216e3d363895fcee7fb4 should at least fix the  creating of the default contour.yml file on CRLF platforms (Windows).

**Comment by sonulohani** [comment]
Thanks for fixing the issue. I verify that the issue is fixed now.
