### ISSUE TITLE
Support Compose-Key

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#144]
Compose key does work on at least X11 (I'd think on any platform).

**Comment by heitzmann** [comment]
Here's the `.XCompose` I use, if it helps.
(Github won't allow me to attach the file with that name, so I renamed it to [XCompose.log](https://github.com/christianparpart/contour/files/5530680/XCompose.log))

**Comment by christianparpart** [comment]
This is already half implemented via Qt native API's. Half, because the visual feedback is missing. I hope I can get that in for the next release.

**Comment by christianparpart** [comment]
was comparing now against KDE konsole with my standard composed keys I used for testing. I didn't get any visual feedback. I'd like to have that though as I remember i have seen that *somewhere*. /closing for now as IME itself is implemented.
