### ISSUE TITLE
0.1.0 (and 0.1.0-pr6) crashes on load on Windows

### ISSUE THREAD

**Issue by whisperity** [christianparpart/contour#152]
## Description

Releases `0.1.0` and `0.1.0_prerelease-6` can't start on Windows, the app crashes immediately. `0.1.0_prerelease-5` works.

## Environment

- Contour Version or Git commit hash: a219a1923692b5e22d0b7d9787eebfe55ca891e2, 9e509ba1ffa63dd0acdaa662d88cc36a63daf4f9
- Operating System (name / distribution / version): Windows 10 x64 19.09
- Contour configuration: *None.* The binary crashes before it could produce the default configuration. If using the default configuration created by `0.1.0_prerelease-5`, it does not change the result.
- TERM environment variable: (Not applicable.)
- Compiler version: (Not applicable.)

## Steps to Reproduce

Download the Windows ZIP release and try to start it. Nothing happens. After going to *reliability monitor*, the crash is shown.

## Crash report

~~~
Source
contour.exe

Summary
Stopped working

Date
‎2020. ‎12. ‎25. 22:41

Status
Report sent

Description
Faulting Application Path:	C:\Users\Whisperity\Downloads\Contour-0.1.0-win64\bin\contour.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	contour.exe
Application Version:	0.0.0.0
Application Timestamp:	5fe49875
Fault Module Name:	Qt5Gui.dll
Fault Module Version:	5.15.2.0
Fault Module Timestamp:	5fa4ddbb
Exception Code:	c0000005
Exception Offset:	0000000000081f47
OS Version:	10.0.18363.2.0.0.256.48
Locale ID:	1038
Additional Information 1:	11d7
Additional Information 2:	11d7eff367329974f87f4ce0ca71ed1c
Additional Information 3:	14c2
Additional Information 4:	14c2b196faec858ee5936b92ee706ab0

Extra information about the problem
Bucket ID:	81494e36865575fb1b1446d8c0dc0213 (1951262435320791571)
~~~

`0xc0..05` is Windows-speak for segmentation faults.

**Comment by christianparpart** [comment]
Thanks @whisperity .

I will be taking care of this and keep you posted.

Many thanks, and merry Christmas.

**Comment by christianparpart** [comment]
I think I have fixed it in b7ff5dfba5a46df8baead9c7f883adfbb79fa70b - at least it fixes it for me.
Will be releasing a new binary soon.

**Comment by whisperity** [comment]
Unfortunately I don't have a compiler on Windows to test. 😦 You should enable each build to have the result uploaded as an artefact for the run, even if it is not a release! For public OSS repositories, both Actions minutes and artefact storage is free. (For private, you get 2k minutes per month and 2 GiB storage total.)

**Comment by christianparpart** [comment]
Hey. I just released v0.1.1 containing the potential fix (and others). 

If that didn't fix it for You, please simply reopen this bug then.

Happy new year! 🥳🍸

**Comment by christianparpart** [comment]
Ah. Please keep in mind: VT feature set is sadly limited to what Windows' ConPTY supports (no Sixel). And sadly on windows platform, contour doesn't support font {matching, fallback, emoji} just yet.

**Comment by whisperity** [comment]
Checked the ZIP in the release and can confirm it works again! 😁 

I'm already humbled by the fact that you dared to look and develop for Windows. But even on Windows, much I use terminals for is either local Git operations, or to SSH away.

Speaking of which, is not having the ability to use the mouse inside Contour is a thing of Windows (MinTTY/Git Bash transmits clicks properly), or just not yet developed at all?

**Comment by christianparpart** [comment]
I check what mintty is doing
