### ISSUE TITLE
Using contour as external terminal in vscode doesn't work as expected

### ISSUE THREAD

**Issue by singalhimanshu** [christianparpart/contour#165]
## Description
Using contour as an external terminal in vscode doesn't open in correct (or expected) directory.

## Environment

- Contour Version or Git commit hash: 730a2621d447ad829cd66bfae03d7715835efea2
- Operating System (name / distribution / version): arch linux
- Contour configuration: default config
- TERM environment variable: `xterm-256color`
- Compiler version: `gcc version 10.2.0 (GCC)`                                                                                                                                   

## Steps to Reproduce
1. Set `Linux exec` to contour - 
![issue](https://user-images.githubusercontent.com/27463862/106149507-5c87d700-61a0-11eb-8f93-92c08ee1e8f9.png)
2. Open terminal using Ctrl+Shift+C.

## Expected Behaviour:
It should open in the project directory rather than home directory.

**Note**: When using alacritty as exec for external terminal it works as expected.

**Comment by christianparpart** [comment]
I just fixed this in 4321dd7e6d8019f85f98f4b1e371f2f635fac8d2 on `master` branch. Many thanks :)
