### ISSUE TITLE
Set some environment variable if shell is running inside Contour

### ISSUE THREAD

**Issue by whisperity** [christianparpart/contour#167]
## Abstract

I would like to have *some* environment variable automatically set by Contour, so the shells running inside may know they are running in Contour.

When a shell is run inside Konsole, you get a few env vars to at least check their existence and be in the know:

```
╰─ env | grep KONSOLE
KONSOLE_DBUS_SERVICE=:1.37
KONSOLE_DBUS_SESSION=/Sessions/10
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_PROFILE_NAME=Default (ZSH)
```

## Motivation

I am using the `conceal` feature in Vim. Conceal allows you to change keywords and sequences to a single letter. E.g. in C++, I am changing `bool` to `𝔹`, `true` to `⊤` and  `false` to `⊥`. This makes Vim show code when reading like below.

Unfortunately, **Konsole** (KDE's terminal emulator I'm using normally) has issues with rendering Unicode. Note how the right-hand sidebar is wobbly, and how in the initialisation of the bool local variables, the `⊥` just randomly went missing.

![Screenshot_20210217_131849](https://user-images.githubusercontent.com/1969470/108203350-aec67300-7122-11eb-8b8c-7bc04f39e6f0.png)

So instead, I use a different glyph for the `false` keyword, `⟂`. They might look similar, but they ain't. [Even Wikipedia mentions the difference between the two symbols.](http://en.wikipedia.org/wiki/Up_tack)  While this makes the disappearing symbol issue fixed, it looks ugly...ish. Note the issue with this symbol is shown, but the wobbly is still there.

![Screenshot_20210217_132137](https://user-images.githubusercontent.com/1969470/108203641-11b80a00-7123-11eb-8ad4-3e7db0f15823.png)

If there was *some* environment variable set by Contour, I could write my Vim scripts in a way that they show the `⟂` glyph instead of `⊥` when I'm in Konsole (or rather, disable this whole feature altogether because of the Unicode rendering issues of Konsole), and use the real `⊥` symbol (and have the conceal feature enabled) when Contour is running.

## Specification

I'm not sure what kind of env-var could be useful. But if there is "something" that starts with `CONTOUR_` and I could grep for it similarly to `KONSOLE_`, it's already fine for scripting user-facing stuff.

**Comment by christianparpart** [comment]
I had the very same think in mind last weekend, when I was adding the integrations shell script (https://github.com/christianparpart/contour/blob/master/contour-integration.zsh) into my `.zshrc`, that also gets then loaded by other terminal emulators I use for testing, and they complain about unknown VT sequences.
I'd suggest to use something that might potentially be picked up by other terminals, too, so not a `CONTOUR_` prefix but more like `TERMINAL_`:

```sh
TERMINAL_NAME=$CanonicalTerminalName
TERMINAL_VERSION=$SemanticVersionTriple
```
I'm not sure more would be of interest.

WRT your glyph issue in Konsole, that is because it may interpret the one glyph in question with width 2 instead of 1. This has changed between Unicode version 8 and 9+ (some with width 1 became width 2). iTerm for example has a configure option to the user to decide how to treat them. By Unicode Emoji standard, all emojis (emoji emoji AND emoji text presentations) should be handled as square characters (width: wide instead of narrow), but the terminal emulator and app community is very slow in adapting I think (if not sometimes even resisting).

**Comment by whisperity** [comment]
Yeah, it's specific to Konsole. I've yet to check the feature in PuTTY/KiTTY (as the other containers I use on servers for dev from my Windows machine do not have the "conceal scripts" set already), but assuming I want to use the conceal stuff (which I'm still debating, it makes me look like a mathematician with all the weird glyphs :wink: ) then it would be the fine reason to jump ship and start using Contour for day-to-day life.

**Comment by whisperity** [comment]
Oh yes, something like `TERMINAL_EMULATOR_*` would be nice. And I guess not that hard to propose and maybe even patch into other terminal emulators in the weeks following because it *should* be a simple addition...

For now, I think I'll do something like "if KONSOLE then noconceal else conceal" to make sure I do not get the wibbly-wobbly.

Konsole has other issues with special glyphs, such as this vim plugin that shows my battery life does not respect the spacing around the gylph. But if I use a conventional letter, it is spaced proper.
![Screenshot_20210217_133749](https://user-images.githubusercontent.com/1969470/108205433-5b095900-7125-11eb-9c42-09c0a4f48737.png)

On the other hand, Contour shows a box:
![Screenshot_20210217_133831](https://user-images.githubusercontent.com/1969470/108205492-6f4d5600-7125-11eb-8f9d-acca443fa2ba.png)

Why is this so hard...

**Comment by christianparpart** [comment]
the latter glyph (symbol_discharging) is due to font-fallback. It did not find the glyph in the font fallback chain, starting from your configured (matched) font, down the priority list as provided by font-config. The requirement for contour that these fonts is that fontconfig and the font itself declare these font as "monospace", and I think the glyph you configured is in your case coming from a font that is not monospace, and that is why contour skips that one font. Do you mind telling me which font that gfyph contains in your configuration? (in case you can find out or you know).

**Comment by christianparpart** [comment]
wrt. these two environment variables, do you want to create a PR for that? If not, that's fine, I'll do it then quickly.

**Comment by whisperity** [comment]
Basically I'm using `JetBrains Mono`. The system is set to use `Noto Sans` for everything and `Hack` (that's the font's name!) for Monospace, according to KDE's "control centre".

Is there a "way" to figure out which font is used there? Because... Konsole is set to use "JetBrains Mono" too and I don't see other settings.

**Comment by whisperity** [comment]
But the thing is, even setting "Font Awesome", which **should** be used by my prompt, is showing bad glyphs in the prompt line itself. There should be some cogs there, and a chart "emoji", etc. Powerline's cfg supposedly uses "Font Awesome" for these.

Contour:
![Screenshot_20210217_165841](https://user-images.githubusercontent.com/1969470/108230796-6a969b00-7141-11eb-9f5e-8a5a40a79721.png)

Konsole:
![Screenshot_20210217_165844](https://user-images.githubusercontent.com/1969470/108230803-6c605e80-7141-11eb-9e94-aa4586f2bdef.png)

**Comment by whisperity** [comment]
Oh there's a debug option! Here's a debug log for generating that line for `/etc/fonts`:

~~~~
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+e0b2
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints:   (presentation: text/Text) (U+E0B2)
        with metrics: (1209+0+0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 13x25+19+0, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 1209: text; ratio:1.0; yOverflow(0, -1); rasterized_glyph(0, 13x25+19+0, 0)
[terminal_renderer/TextRenderer.cpp:452:getTextureInfo] Cropping 1 underflowing bitmap rows.
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+32 U+2e U+38 U+39
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints: 2.89  (presentation: text/Text) (U+0032 U+002E U+0038 U+0039)
        with metrics: (541+0+0) (574+0+0) (547+0+0) (548+0+0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 9x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 541: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 9x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 547: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 548: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 10x14+14+1, 0)
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+f080
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=4, path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=5, path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=6, path="/usr/share/fonts/type1/gsfonts/n022003l.pfb"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=7, path="/usr/share/fonts/truetype/tlwg/TlwgTypo.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=10, path="/usr/share/fonts/opentype/firacode/FiraCode-Regular.otf"
[text_shaper/open_shaper.cpp:580:shape] Shaping failed.
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints:   (presentation: text/Text) (U+F080)
        with metrics: (0+0+0)
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+31 U+37 U+3a U+30 U+30 U+3a U+30 U+36
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints: 17:00:06  (presentation: text/Text) (U+0031 U+0037 U+003A U+0030 U+0030 U+003A U+0030 U+0036)
        with metrics: (540+0+0) (546+0+0) (576+0+0) (539+0+0) (539+0+0) (576+0+0) (539+0+0) (545+0+0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 540: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 546: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 9x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 539: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 9x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 10x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 545: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 10x14+14+1, 0)
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+f017
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=4, path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=5, path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=6, path="/usr/share/fonts/type1/gsfonts/n022003l.pfb"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=7, path="/usr/share/fonts/truetype/tlwg/TlwgTypo.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=10, path="/usr/share/fonts/opentype/firacode/FiraCode-Regular.otf"
[text_shaper/open_shaper.cpp:580:shape] Shaping failed.
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints:   (presentation: text/Text) (U+F017)
        with metrics: (0+0+0)
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+2570 U+2500
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints: ╰─  (presentation: text/Text) (U+2570 U+2500)
        with metrics: (924+0+0) (934+0+0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 8x15+21+4, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 924: text; ratio:1.0; yOverflow(-1, 0); rasterized_glyph(0, 8x15+21+4, 0)
[terminal_renderer/TextRenderer.cpp:443:getTextureInfo] Cropping 1 overflowing bitmap rows.

[...]

[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+f013
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=4, path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=5, path="/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=6, path="/usr/share/fonts/type1/gsfonts/n022003l.pfb"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=7, path="/usr/share/fonts/truetype/tlwg/TlwgTypo.ttf"
[text_shaper/open_shaper.cpp:576:shape] Try fallback font: key=10, path="/usr/share/fonts/opentype/firacode/FiraCode-Regular.otf"
[text_shaper/open_shaper.cpp:580:shape] Shaping failed.
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints:   (presentation: text/Text) (U+F013)
        with metrics: (0+0+0)
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+32 U+2e U+38 U+31
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints: 2.81  (presentation: text/Text) (U+0032 U+002E U+0038 U+0031)
        with metrics: (541+0+0) (574+0+0) (547+0+0) (540+0+0)
[text_shaper/open_shaper.cpp:549:shape] Shaping codepoints: U+31 U+37 U+3a U+30 U+30 U+3a U+34 U+30
        Using font: key=0, path="/usr/local/share/fonts/j/JetBrainsMono-Regular.ttf"
[terminal_renderer/TextRenderer.cpp:251:shapeRun] Shaped codepoints: 17:00:40  (presentation: text/Text) (U+0031 U+0037 U+003A U+0030 U+0030 U+003A U+0034 U+0030)
        with metrics: (540+0+0) (546+0+0) (576+0+0) (539+0+0) (539+0+0) (576+0+0) (543+0+0) (539+0+0)
[terminal_renderer/TextRenderer.cpp:346:getTextureInfo] Glyph metrics: rasterized_glyph(0, 9x14+14+1, 0)
[terminal_renderer/TextRenderer.cpp:417:getTextureInfo] insert glyph 543: text; ratio:1.0; yOverflow(0, 0); rasterized_glyph(0, 9x14+14+1, 0)
~~~~

**Comment by christianparpart** [comment]
wow, nice, that's even a very recent git version. I'll check ASAP. Many thanks.

**Comment by whisperity** [comment]
Fun fact: the glyphs as copied to you do not render in the browser, either!

In the order of the glyphs in the copied text, it should be a leftwards triangle, a chart, a clock, the north center -> west middle "clamp" of the prompt char, and a cogwheel.

As for the recentness, I just did this today because I can't put together a dev env but the CI does not create tarballs only at the point of release: http://github.com/whisperity/contour/actions/runs/574825166

**Comment by christianparpart** [comment]
I've added 3 environment variables for terminal identification in 8459b61bb369ad2cdff8f2bc913592a098ab21a0. What do you think about them? Anything missing? (That's currently living in `wip` branch so I can potentially amend the commit with updates)

**Comment by christianparpart** [comment]
The unicode codepoints U+f080, U+f017, U+f013 all are in the range of the private use area. So you must have some special font installed that does provide these codepoints with a specific meaning. - is this Powerline? (I don't know). I think why contour does skip them is because it's filtering out everything that is not monospace during font fallback.

**Comment by whisperity** [comment]
Oh nice, thanks for figuring it out. I do not have "Nerd Fonts" installed, but I do have *Font Awesome* installed, so it should come from there.

But even if I set in contour.yml:

```
permissions:
  change_font: allow
font:
  only_monospace: false
  regular: "FontAwesome"
```

the result is still broken glyphs.

(I did not update the build yet!)

**Comment by christianparpart** [comment]
After my complete font/shaking rewrite i am not YET honoring only_monospace. I will fix this ASAP

**Comment by whisperity** [comment]
> I've added 3 environment variables for terminal identification in [8459b61](https://github.com/christianparpart/contour/commit/8459b61bb369ad2cdff8f2bc913592a098ab21a0). What do you think about them? Anything missing? (That's currently living in `wip` branch so I can potentially amend the commit with updates)

Lovely, thanks. Somethingsomething contains "contour" is good enough for me with the ligatures, and I hope it'll be a useful feature for others.

**Comment by christianparpart** [comment]
With this commit I think I can now close this ticket, and with regards to fonts, either open a specific new ticket in case you can precisely describe that issue, or we just collect that into the font rendering tracker issue #156.

**Comment by whisperity** [comment]
Also, I realised, there has been an `environment` section in the config file from the start... Could've just written it there by default.

**Comment by christianparpart** [comment]
> 
> 
> Also, I realised, there has been an `environment` section in the config file from the start... Could've just written it there by default.

I agree, however, having  a somewhat standardized form of names and values for those variables is absolutely helpful for both, users and TE devs.

**Comment by whisperity** [comment]
Circling back to this, it seems `TERMINAL_NAME` is only a viable choice if the shell is running locally, as -- by default -- it is not propagated through SSH.

Considering we now have a working(-ish?) terminfo file, this feature could be deprecated?

**Comment by christianparpart** [comment]
> Circling back to this, it seems `TERMINAL_NAME` is only a viable choice if the shell is running locally, as -- by default -- it is not propagated through SSH.
> 
> Considering we now have a working(-ish?) terminfo file, this feature could be deprecated?

Did you try this? https://superuser.com/a/48787/145329

**Comment by christianparpart** [comment]
Most reliable would be the use of XTVERSION VT sequence though

**Comment by whisperity** [comment]
> Most reliable would be the use of XTVERSION VT sequence though

From a (potentially non-interactive) script that gets sourced when the shell is loaded?

**Comment by whisperity** [comment]
> > Circling back to this, it seems `TERMINAL_NAME` is only a viable choice if the shell is running locally, as -- by default -- it is not propagated through SSH.
> > Considering we now have a working(-ish?) terminfo file, this feature could be deprecated?
> 
> Did you try this? https://superuser.com/a/48787/145329

I don't want to, because it's not proven whether the remote end will have contour installed or contour capabilities. And it is not always the case that I SSH in *from Contour*. So it has to work in a fully dynamic fashion.
