### ISSUE TITLE
Keybinds to function keys are weirding out

### ISSUE THREAD

**Issue by whisperity** [christianparpart/contour#172]
## Description

Function keys `F2`, `F3`, `F4`, `S-F2`, etc. do not work as expected.

## Environment

- Contour Version or Git commit hash: ee01691
- Operating System (name / distribution / version): Ubuntu 18.04
- Contour configuration: Default
- TERM environment variable: `xterm-256color`

## Steps to Reproduce

I have the following configuration for my Vim.
I do have more elaborate stuff, but I tested with **just** this configuration in a plain environment and the issue still persists.

```vim
" Buffer switch.
nnoremap <silent> <F2> :buffers<CR>:buffer<Space>
nnoremap <silent> <F3> :bprevious <CR>
nnoremap <silent> <F4> :bnext <CR>
```

When I use Vim through Konsole, these keybinds work. When I do it through Contour, they don't.
Done through Contour, pressing F3 or F4 randomly deletes lines and goes from NORMAL to REPLACE mode (because of the `R` character in the sequence, I believe).

It seems the two emulators send different sequences w.r.t. the function keys:

Konsole:

~~~
╰─ cat
NORMAL F2 ^[OQ
NORMAL F3 ^[OR
NORMAL F4 ^[OS
CTRL F2
CTRL F3 ^[O5R
CTRL F4 ^[O5S
SHIFT F2 ^[O2Q
SHIFT F3 ^[O2R
SHIFT F4 ^[O2S
~~~

Contour:

~~~
╰─ cat
NORMAL F2 ^[0Q
NORMAL F3 ^[0R
NORMAL F4 ^[0S
CTRL F2
CTRL F3 ^[[1;5R
CTRL F4 ^[[1;5S
SHIFT F2 ^[[1;2Q
SHIFT F3 ^[[1;2R
SHIFT F4 ^[[1;2S
~~~

Also note how `Ctrl`-`F2` does not produce a result. It might be something with this particular computer, but I can't seem to figure out why.

**Comment by whisperity** [comment]
gnome-terminal:

~~~
NORMAL F2 ^[OQ
NORMAL F3 ^[OR
NORMAL F4 ^[OS

SHIFT F2 ^[[1;2Q
SHIFT F3 ^[[1;2R
SHIFT F4 ^[[1;2S

CTRL F2 
CTRL F3 ^[[1;5R
CTRL F4 ^[[1;5S
~~~

However, what is strange: if I go into *Vim* from `gnome-terminal`, the F3-F4 keybinds work for swapping left and right between buffers... Even though according to `cat` it seems that the input sequence generator odd one out **is** Konsole...

**Comment by whisperity** [comment]
It's only F2-F3-F4 that is weird (and I guess F1, too). F5 and onwards seem to work fine, both Konsole, Contour and Gnome generate `^[[15~`, which Vim picks up for my Undotree keybind:

```
map <silent> <F5> :UndotreeToggle<cr>
```

**Comment by whisperity** [comment]
This is not a Vim-specific issue, however. My keybinds for F2-F3-F4 on buffer switch come from the similar keybinds of `byobu` (a `tmux` "wrapper" I guess?) where F2 is new tab, and F3-F4 is motion between tabs left and right. Similarly, the keybinds do not work through Contour.

**Comment by christianparpart** [comment]
Fixed and merged to master. Many thanks @whisperity!
