### ISSUE TITLE
Implement a keybind/action/timer that forces the looks of the terminal back to user setting

### ISSUE THREAD

**Issue by whisperity** [christianparpart/contour#177]
## Abstract

For some reason, Vim tends to change the cursor shape to BLOCK when terminal mode (such as FZF's search, see https://github.com/junegunn/fzf.vim/issues/1059) is used. It most definitely does that by emitting some escape sequences. And then, it remains a BLOCK, even after I quit.

There is no way through Contour to reset the cursor shape "from the inside" (without manually figuring out the escape sequence).

 1. Configure `cursor.shape: "bar"`.
 2. Say `echo -en "\033[2 q"`. Cursor becomes a block.
 3. No way back, without either restarting, or knowing you have to say `\033[6 q` which makes it become an i-beam again

## Specification

Saying `reset` on the inside doesn't help. So there should be an enum constant for the keybinds/mapping action, and should be mapped to some reasonable default (or maybe not mapped at all) which will make the emulator emit on itself the escape sequences needed to reset to how the user originally configured.

While the issue in particular is about cursor shape, maybe it can gradually be increased to involve everything, like colours, and whatnot.

**Comment by christianparpart** [comment]
Try this in your input mapping section:
```yaml
input_mapping:
    - { mods: [Control, Alt], key: B, action: WriteScreen, chars: '\e[6 q' } 
    - ...
```
Then in your terminal, press <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>B</kbd>.
You can even go and add some more of these modes to change cursor style on the fly, just for testing / show-casing purposes.

So, I think I can close this then right away? We can re-open in case I did misunderstand something. :)

**Comment by whisperity** [comment]
Oh, you can map sequences. Neat. I side-stepped the issue with a Vim plugin... turns out Konsole was "disrespecting" Vim trying to change the cursor from the very start, every other terminal emulator would've changed the cursor (such as alacrity or dumped the random escape sequences (such as gnome-terminal), **but** Konsole.
