### ISSUE TITLE
Keybind that toggles all other keybinds

### ISSUE THREAD

**Issue by whisperity** [christianparpart/contour#185]
## Abstract

Offer a bindable option that toggles the capturing of all other keybinds. Related to #182. Also, the `keyPressEvent` logging should be improved to explicitly tell whether a keybind was received and what keybind (kind, at least) was executed

## Motivation

#182. Also, `byobu` has a special keybind among its F-keys, I think `Shift`-`F12`, which basically toggles all byobu-specific keybinds. I.e. when you are using `htop` or `mc` (which uses F-keys) **inside** `byobu` you have to turn off the keybinds of `byobu` first so the keybinds are forwarded to the program. A similar functionality would be appreciated.

## Specification

1. A new keybind action kind (enum value), let's say `ToggleKeybinds` or `ToggleInputMappingCapture`.
2. This should be bound to something by default. I would suggest the same `Shift`-`F12` sequence.
3. If the user presses this keybind, a global flag is toggled that the user disabled keybind capturing.
4. Any subsequent key press that *might* match a keybind is ignored, unless, of course, it is the keybind for this new toggle, so the toggle still works.

In addition, the logging in `keyPressEvent` should explicitly log if a key sequence that was received:
 - matches a keybind or not
 - if it matches a keybind, the key action (e.g. `ChangeProfile` and the other enum values) should be printed to the log (with a string identifier, preferably, not the enumerator value): `keyPressEvent: got keybind ScrollUp`
 - if matched and keybind capture is turned off, the log should reflect this, e.g. `keyPressEvent: got ScrollUp, ignoring because capture turned off`

**Comment by christianparpart** [comment]
Ref: https://www.byobu.org/

**Comment by christianparpart** [comment]
Done in https://github.com/christianparpart/contour/commit/aecadc00b230334da602d6f4d9d1927ad7b4cdfd.
