### ISSUE TITLE
Fix build when using libfmt (fmtlib) as system dependency on at least Ubuntu

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#189]
The recent PR #187 removed git submodules and greatly improved flexibility wrt. build dependencies, however libfmt on Ubuntu (20.10 at least) is broken due to how it is addressed in the cmake files.

**Comment by avemilia** [comment]
Right now I have no space on disk left to install the VM to see what the error is and test, so anyone, feel free to pick up. It would be helpful if you at least posted the error message, maybe somebody can just look at it and say what is wrong.

Anyway, the relevant code is https://github.com/christianparpart/contour/blob/755b7959c801f6373b3065211b684e35798afbbd/CMakeLists.txt#L65-L71

so in my understanding it can only break in two cases: fmt in Ubuntu doesn't provide `fmt::fmt-header-only` target (which I took from official docs and confirmed in `/usr/lib/cmake/fmt/fmt-targets.cmake` on my system) or fmt is simply not installed.

**Comment by christianparpart** [comment]
Good morning. I will post it here and will also try to look at it by the end of next week, maybe on-stream again into it. :)

**Comment by christianparpart** [comment]
hmm... I settled on not using system deps on those 4 libraries. embedding is way to easy. we can re-open at any time again if time permits :)
