### ISSUE TITLE
Weird "rolling" font rendering issue

### ISSUE THREAD

**Issue by whisperity** [christianparpart/contour#194]
## Description

There is some odd "rolling shutter" like glitch in rendering letters. Letters that fall into the same column inside the viewport will all be distorted in the same way (around the same "distance" when measured against the width of the letter's block).

Pictures speak better than words here, see below!

## Environment

- Contour Version or Git commit hash: Prelelease 0.2.0, Build 264
- Operating System (name / distribution / version): Ubuntu 18.04.5 LTS
- Contour configuration: JetBrains Mono font.
- TERM environment variable: xterm-256color
- Compiler version: GitHub

## Steps to Reproduce

Type in letters to the terminal, at least 10-20 in a row.

## Details

Look at the `/`s in the picture, noting the `/` that is part of the "current directory". Both `/` above and below it is broken in the same way. Similar to all the other broken glyphs. It seems to happen once roughly every 10 columns. Note also the `l` in **`l`**`oaded`.
![image](https://user-images.githubusercontent.com/1969470/110600456-3cc2d600-8184-11eb-9012-b6d697f03ca6.png)

However, it is not restricted to the `/` letter. It seems the only determining factor on both the existence and the kind of the glitch is which column the glyphs was rendered to.
![image](https://user-images.githubusercontent.com/1969470/110600546-56fcb400-8184-11eb-8d9c-2bdc5cb3fbb9.png)

If you check the first `s` below the `/` so in the same column, that `/` is bogus, and so is the `s` in the same column. The `s` under a normal `/` (below the `G` in `SIGINT`) looks normal.
However, the `N` in `SIGINT` also looks broken in the middle, just like how in the same column both `/` and the `l` of `self` is **also** affected similarly.
![image](https://user-images.githubusercontent.com/1969470/110600642-7267bf00-8184-11eb-9f39-c4a46a56a4be.png)

Compare the bottom left corner of the `/` and the left side of the `s` with the other `s`. There is a few pixel wide glitch there, on both.
![image](https://user-images.githubusercontent.com/1969470/110600750-90cdba80-8184-11eb-863f-d6489eaa2341.png)

Now the `/` on the top right has a bit of a glitch, and so is the `l` which bottom right part is longer than the other `l`'s (which `/` in the same column isn't glitching)
![image](https://user-images.githubusercontent.com/1969470/110600761-95926e80-8184-11eb-9969-6843021c9138.png)

If you check the rightmost `f` here, it has a bit of a glitch to the left of the "trunk" of the `f`. And just in the same position above, the `/` has a bit of a glitch... at around 30% of the total "width" of the glyph.
The previous `f` on the left which has a clear `/` above it doesn't suffer from the glitch.
![image](https://user-images.githubusercontent.com/1969470/110600784-9a572280-8184-11eb-9f9e-11dbc0af3f88.png)

The `9`s in the date are deterministically broken in that column. However, look at the number **just before** the `/` like `82/85` and `83/85`. The `2` and `3` is broken, because they are in the same column.

What's more, in the bottom 5 lines, where the same column is now showing a `/` instead of a number (because the left number is 1 digit long only), it is the `/` that is broken. Look closer at the `e` in `Pr`**`e`**`-analysis` and and the `a` in `St`**`a`**`rting`, which fall onto the same column, they are bonkers too.
Just as how the column of `c` in **`c`**`langsa`, all the `c`s are broken. The `y` in `Pre-anal`**`y`**`sis` in the same column, and all the 1st letters of the filenames printed above, suffer from the glitch, at basically the same position inside the glyph.
![image](https://user-images.githubusercontent.com/1969470/110600971-c96d9400-8184-11eb-8030-1ed55e799e8a.png)

Here's the previous image zoomed in and some of the affected columns highlighted.
![image](https://user-images.githubusercontent.com/1969470/110601030-d25e6580-8184-11eb-8f82-769eb439481c.png)

**Comment by christianparpart** [comment]
thanks for the wrapup! :)

**Comment by christianparpart** [comment]
![image](https://user-images.githubusercontent.com/56763/110761602-37cb5880-8250-11eb-879a-bcfc8078f950.png)
this also shows it quite cleary I think

**Comment by whisperity** [comment]
If you change the font size, the pattern changes and appears in different locations, but it's still appearing.
