### ISSUE TITLE
VT mouse in Vimspector scrolls on mouse move inside the editor window

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#200]
Not sure yet why, but it does.

**Comment by whisperity** [comment]
Maybe crucial information, but it always scrolls **up**.

**Comment by christianparpart** [comment]
> Maybe crucial information, but it always scrolls **up**.

only scrolls up regardless on mouse-move (up/down/left/right). however, only when within the source code window.

Also - this behaviour does not happen on neovim, there the mouse works as expected.

I suspect that there might be one (event protocol / transport protocol) combination that I didn't expect and seems to trigger this bug in vim+vimspector's source code window.

**Comment by whisperity** [comment]
Not just the source code window, at least not for me. It scrolls the bottom window (gdb output?) too.

**Comment by christianparpart** [comment]
Fixed.
