### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by codic12** [christianparpart/contour#223]
I'm running on Arch linux, and can't compile the project. It looks like a dependency crispy uses requires std::source_location, a C++ 20 feature: https://hastebin.com/ahakafebew.rb

It looks like it sets std=c++1z, instead of 2x :thinking:

**Comment by christianparpart** [comment]
Hey. Many thanks for your interest. I am already aware of this problem and it sadly got introduced with my last PR merge last night. I will address that tomorrow. (I sadly don't have an Arch around)

**Comment by codic12** [comment]
Very fast response, thank you! I was able to set C++ 20 in CMakeLists.txt and that issue is gone, but I don't know if that is the proper solution or if it's better to rewrite to support C++ 17

Another issue, in font.h optional is not included, so I get errors referencing std::optional not found. I'll try #includ'ing <optional> and try again.

**Comment by uspasojevic96** [comment]
In the mean time, you can build the latest commit (25950d6) that passed for Arch Linux, or you can download the release from releases page

**Comment by christianparpart** [comment]
to be honest, that is a proper fix. However for those platforms that do NOT have `std::source_location` available (some compilers have it in C++17 mode already) I do provide a fallback. I wonder why it didn't catch on Arch. Maybe I should just set it to C++20 then. if that works on all platforms without problems.

**Comment by christianparpart** [comment]
What compiler version is that on Arch? It almost feels like a downgrade, especially since the `std::source_location` part I didn't even touch in the PR. That doesn't make sense (to me). The problem with libunicode is most likely a non-conforming compiler that doesn't play nice with the extensive use of C++ features. I'll check that., too.

**Comment by uspasojevic96** [comment]
> to be honest, that is a proper fix. However for those platforms that do NOT have `std::source_location` available (some compilers have it in C++17 mode already) I do provide a fallback. I wonder why it didn't catch on Arch. Maybe I should just set it to C++20 then. if that works on all platforms without problems.

Well, Arch has newer packages than ubuntu, so in theory it should have everything already (latest llvm, gcc...). I will check this on one of my VMs

**Comment by codic12** [comment]
the only C++ compilers i have installed are clang++ and g++, not sure which it is picking but both should be quite compliant with C++ standards

**Comment by christianparpart** [comment]
I've found the build issue in libunicode and committed  a fix in that repo already

https://github.com/christianparpart/libunicode/commit/068199f65d3e9ed382074aa96d4c2f3ad5716903

I'll update this repo to fetch the updated libunicode tomorrow.

**Comment by fake-rookie** [comment]
Same using `Arch Linux` here.

Nothing problem with **std::optional**.

![1](https://i.postimg.cc/nCw87krS/2021-05-27-190756-914x828-scrot.png)

![2](https://i.postimg.cc/687khvGW/2021-05-27-190825-326x92-scrot.png)

**Comment by uspasojevic96** [comment]
A bit of an update:

- It happens on GCC 11+
- Changing C++ version to 17 fixes part of the issue
- Other issue that arises is with `crispy::source_location`
- GCC 10 works (tested on Gentoo)

**Comment by christianparpart** [comment]
Hey, I've been fixing that for GCC 11+ (it seemed they have been removing C++ API functionality? - plus the one missing include that didn't occur earlier).

**Comment by codic12** [comment]
Confirmed it's fixed. Looks very feature-complete so far, let's see how well it holds up!
