### ISSUE TITLE
Synchronized output documentation is out of date

### ISSUE THREAD

**Issue by j4james** [christianparpart/contour#236]
I noticed that your wiki documentation for the synchronized output mode is still listing the original number you proposed (2001) rather than the one that was eventually agreed on (2026). See here:
 
https://github.com/christianparpart/contour/wiki/VTExtensions#synchronized-output

**Comment by christianparpart** [comment]
Oh what a finding! Many thanks @j4james. I've fixed that and added some "Adoption state" sub-section. I'll investigate more in the future who else has or might be willing to adopt. Thanks :)
