### ISSUE TITLE
Provide cell-pixel geometry in TIOCGWINSZ

### ISSUE THREAD

**Issue by dankamongmen** [christianparpart/contour#241]
## Abstract

Contour's implementation of the `TIOCGWINSZ` `ioctl(2)` doesn't fill in the following two optional fields:

```c
               unsigned short ws_xpixel;   /* unused */
               unsigned short ws_ypixel;
```

Contour supports Sixel. Unfortunately, without this knowledge, it's difficult to use Sixel correctly for anything but trivial work.

## Motivation

These fields ought be filled in, as they are by most terminals supporting bitmap graphics (all of which I am aware).

## Specification

When `TIOCGWINSZ` is answered by Contour, the `ws_xpixel` field ought be filled in with the number of native pixels per cell width, and `ws_ypixel` ought be filled in with the number of native pixels per cell height.

When the cell-pixel geometry changes (for instance in response to a font change), the information ought be updated in subsequent `ioctl(2)`s, and ideally a `SIGWINCH` ought be delivered as it would upon a cell geometry change.

see https://github.com/dankamongmen/notcurses/issues/1805

**Comment by christianparpart** [comment]
Oh.

**Comment by christianparpart** [comment]
Thanks @dankamongmen, I really appreciate your reports. I owe you a beer or two ;-)

**Comment by dankamongmen** [comment]
> Thanks @dankamongmen, I really appreciate your reports. I owe you a beer or two ;-)

i'm strictly a krokodil / bathsalts / adrenochrome man, though i have been known to quaff some Sterno in my time

**Comment by dankamongmen** [comment]
btw i gave the wrong semantics here. i said they should have the cell-pixel geometry; it ought be the window geometry in pixels.

**Comment by dankamongmen** [comment]
confirmed, thanks much holmes!

```
 notcurses 2.3.4 by nick black et al on Contour 0.2.0-unreleased-master-96b8f89
  30 rows (22px) 130 cols (11px) (60.94KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.1 20210110, 16B little-endian cells
  terminfo from ncurses 6.2.20201114
  avformat 58.45.100 avutil 56.51.100 swscale 5.7.100

 colors: 256 rgb: y ccc: y setaf: y setab: y
 sgr: y sgr0: y op: y fgop: y bgop: y
 rows: 30 cols: 130 rpx: 22 cpx: 11 (660x1430)
 sixel colorregs: 256
```

**Comment by dankamongmen** [comment]
```
  Width: 1446
  Height: 660
```

checks out (i've got a scrollbar which could easily be 16 pixels wide)!

**Comment by christianparpart** [comment]
Is this a problem? Just so i understand :)

**Comment by dankamongmen** [comment]
> Is this a problem? Just so i understand :)

nope, just confirming via `xwininfo` that the rematerialized window pixel geometry was reasonable. it was! =]

**Comment by dankamongmen** [comment]
> rows: 30 cols: 130 rpx: 22 cpx: 11 (660x1430)     <----------- `notcurses-info`

> Width: 1446   <--------------------- `xwininfo`
  Height: 660

they're not an exact match, but i think the 16 extra pixels are probably due to the scrollbar.

**Comment by christianparpart** [comment]
Then I shall fix this

**Comment by dankamongmen** [comment]
no it's working! i must not be clear
