### ISSUE TITLE
XTSMGRAPHICS geometry query is answered as cregs query

### ISSUE THREAD

**Issue by dankamongmen** [christianparpart/contour#246]
## Abstract

Using contour from head, I can't seem to draw a sixel over a certain, reproducible size (independent of terminal size). If I do, it gets truncated to the bottom and right. That's fine, but contour doesn't seem to respond to `XTSMGRAPHICS` type-2 query with maximum geometry:

i send `\33[?2;1;0S` and contour replies with `\33[?1;0;800S`. more expansively, i send `33[?1;3;256S\33[?2;1;0S`, and contour responds with `\33[?1;0;256S\33[?1;0;800S`. that second reply needs to be a 2, i believe, and also wants a second number.

## Motivation

I poked around at `Sequencer.cpp` for a bit, wondered how two integers related to a `std::monostate`, wondered when `monostate` became part of `std`, wondered where all the time had gone and whether it had been worth it, and closed the c++ file. Perhaps you can fix this more easily.

## Specification

>  Pi = 1  ⇒  item is number of color registers.
            Pi = 2  ⇒  item is Sixel graphics geometry (in pixels).
            Pi = 3  ⇒  item is ReGIS graphics geometry (in pixels).
            Pa = 1  ⇒  read attribute.
            Pa = 2  ⇒  reset to default.
            Pa = 3  ⇒  set to value in Pv.
            Pa = 4  ⇒  read the maximum allowed value.
            Pv is ignored by xterm except when setting (Pa == 3 ).
            Pv = n ⇐  A single integer is used for color registers.
            Pv = width ; height ⇐  Two integers for graphics geometry.
          xterm replies with a control sequence of the same form:
               CSI ? Pi ; Ps ; Pv S
          where Ps is the status:
            Ps = 0  ⇐  success.
            Ps = 1  ⇐  error in Pi.
            Ps = 2  ⇐  error in Pa.
            Ps = 3  ⇐  failure.

**Comment by christianparpart** [comment]
Oh nice investigation. @dankamongmen I'm having some time to live-stream digg into this report and fix it. :)

p.s.: do you ever sleap, U.Robot? 🤖

**Comment by dankamongmen** [comment]
> p.s.: do you ever sleap, U.Robot? ￼

in honor of john mcafee's untimely death in a spanish prison today, i shall post something once seen inside the walls of mcafee

![mcafee-pays-homage](https://user-images.githubusercontent.com/143473/123209635-e9546980-d48e-11eb-99f0-c0902e72ff95.jpg)

in truth i take hundreds of imperceptible femtonaps each second

**Comment by christianparpart** [comment]
> ## Abstract
> 
> Using contour from head, I can't seem to draw a sixel over a certain, reproducible size (independent of terminal size). If I do, it gets truncated to the bottom and right. 

The configuration file at `$XDG_CONFIG_HOME/contour/contour.yml` there is a part like:

```yaml
images:
    max_width: 800
    max_height: 600
    # ... and others
```
These limits are configurable. But yes, this should be reflected by the response to `XTSMGRAPHICS` somehow.

> That's fine, but contour doesn't seem to respond to `XTSMGRAPHICS` type-2 query with maximum geometry:


> i send `\33[?2;1;0S` and contour replies with `\33[?1;0;800S`. 


> [...] i send `33[?1;3;256S\33[?2;1;0S`, and contour responds with `\33[?1;0;256S\33[?1;0;800S`. that second reply needs to be a 2, i believe, and also wants a second number.

> ## Motivation
> 
> I poked around at `Sequencer.cpp` for a bit, wondered how two integers related to a `std::monostate`, wondered when `monostate` became part of `std`, wondered where all the time had gone and whether it had been worth it, and closed the c++ file. Perhaps you can fix this more easily.

Oh many thanks for your interest though! This is pretty modern C++(17) usage in Contour. 

/me going into fixing mode now. ^^

**Comment by christianparpart** [comment]
I think I fixed it and I do believe I'm doing it the way the `ctlseqs.txt` is wanting me to do it (*praying*).

**Comment by christianparpart** [comment]
@dankamongmen without stressing you too much, would you mind confirming the responses are meating thy expectations?

**Comment by dankamongmen** [comment]
` max sixel size: 600x800 colorregs: 256`

![german-chancellor-angela-merkel-gives-a-thumbs-up-during-the-foundation-stone-laying-ceremony-for-the-start-of-the-new-dfb-german-football-association-headquarters-in-frankfurt-germany-september-26-2019-reutersflorian-ulrich-2CJEX2T](https://user-images.githubusercontent.com/143473/123304097-842f6100-d4ec-11eb-8ed3-05d8c96a8406.jpg)
