### ISSUE TITLE
config file validation (e.g. warn on superfluous keys / invalid values)

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#251]
Maybe with the help of https://github.com/psranga/yavl-cpp (uses yaml-cpp, too, this is good).

This is also going into 0.2.0 as we've quite some config changes in 0.2.0 and this might help migrations now and in the future.

### Checklist:

* [ ] report invalid keys
* [ ] report invalid values
* [ ] missing keys (might be tricky?)

**Comment by whisperity** [comment]
Idea: as contour is continuously evolving, maybe if you do this, it would be nice to warn about *missing* keys too, i.e. if a newer version of contour has new config variables for which not even the default is written into the config file (i.e. "you should update your cfg!").

**Comment by christianparpart** [comment]
> Idea: as contour is continuously evolving, maybe if you do this, it would be nice to warn about _missing_ keys too, i.e. if a newer version of contour has new config variables for which not even the default is written into the config file (i.e. "you should update your cfg!").

That's a very nice point. But what if the user doesn't want to mention defaults in his config because he'd like to keep it slim? hmm... (`config.ignore_missing_keys: true` maybe)

**Comment by whisperity** [comment]
You could timestamp the version or the keys that the user got warned about into `~/.local/share/contour` or something... In which case, each warning for each cfg option only gets shown once...

Or only gets shown once per the terminal is updated, or once per major/minor release, not for every update and definitely not for every started binary.

**Comment by WSLUser** [comment]
Windows Terminal uses 2 json files: 1 for defaults (which can be opened with a keybinding) and another for user specific that can override/add to the defaults. The user specific json utilizes the json schema for validation. Is there a schema for toml available (also creating a default toml file for generally useful default settings that majority of users seem to use based on feedback would be nice.)
