### ISSUE TITLE
Scrollbar placeholder is still visible with configuration setting `hidden`

### ISSUE THREAD

**Issue by NTBBloodbath** [christianparpart/contour#271]
## Description

Scrollbar placeholder is not being removed after hiding the scrollbar in the configurations.

<div align="center">

![Screenshot_20210629_113225](https://user-images.githubusercontent.com/36456999/123826445-c500ee80-d8cd-11eb-999e-6a3e6ab65124.png)

</div>

## Environment

- Contour Version or Git commit hash: master branch (commit `08d648a88dcb4f698ee8bfad73da1e34beb88fa1`)
- Operating System (name / distribution / version): Fedora 34
- Contour configuration: [contour.yml](https://gist.github.com/NTBBloodbath/4e1a645efaf00ec9fac6d7db21ba58ee)
- TERM environment variable: `xterm-256color`
- Compiler version:
  - CMake: `3.20.5`
  - Ninja: `1.10.2`

## Steps to Reproduce

- Set `position` field to `hidden` in the scrollbar section in your configuration file and restart contour

**Comment by christianparpart** [comment]
Oh nice finding. Many thanks @NTBBloodbath . I will fix that ASAP.

**Comment by christianparpart** [comment]
Hey. Would you mind given the branch `fix/scrollbar-not-hidden`  a try? (see linked PR).

**Comment by NTBBloodbath** [comment]
Sure, lemme build it :+1:

**Comment by NTBBloodbath** [comment]
Working like a charm, thank you so much! :heart:

![Screenshot_20210629_140324](https://user-images.githubusercontent.com/36456999/123846116-f7691680-d8e2-11eb-94ae-67dd3f4e78a8.png)

**Comment by christianparpart** [comment]
Oh great! I am glad you tried contour and certainly that you did report the bug. It so makes this software more versatile and stable. Many thanks.
