### ISSUE TITLE
OSX: fix background cell drawing (and cursor drawing)

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/contour#80]
only happens on osx, but cell backgrounds and cursor aren't rendered.

**Comment by swolter** [comment]
[Old Input Mono.zip](https://github.com/christianparpart/contour/files/3671466/Old.Input.Mono.zip)

Here's the version of Input Mono that seems to be causing the issue for me.

**Comment by christianparpart** [comment]
Cell background (**and** cursor) fixed. (with the great help of NVIDIA Nsight Graphics debugger) :)
